# Site settings
title: devBlog
email: saggaf@area54labs.net
description: > # this means to ignore newlines until "baseurl:"
  Hi there! This is my blog mostly talking about Software Development and Technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: saggafarsyad
github_username:  saggafarsyad

# Build settings
markdown: kramdown
